[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
from = "/key/catalog"
to = "/.netlify/functions/catalog"
  status = 200

[[redirects]]
  from = "/key"
  to = "/.netlify/functions/raw"
  status = 200

[[redirects]]
  from = "/key/*"
  to = "/.netlify/functions/raw/:splat"
  status = 200

[[redirects]]
  from = "/clips"
  to = "/.netlify/functions/clipboards"
  status = 200

[[redirects]]
  from = "/clips/*"
  to = "/.netlify/functions/clipboards/:splat"
  status = 200

[[redirects]]
from = "/file"
to = "/.netlify/functions/files"
status = 200

[[redirects]]
from = "/file/*"
to = "/.netlify/functions/files/:splat"
status = 200

[[redirects]]
from = "/apps"
to = "/.netlify/functions/apps"
status = 200

[[redirects]]
from = "/apps/*"
to = "/.netlify/functions/apps/:splat"
status = 200

[[redirects]]
from = "/mod"
to = "/.netlify/functions/modules"
status = 200

[[redirects]]
from = "/mod/*"
to = "/.netlify/functions/modules/:splat"
status = 200

[[redirects]]
from = "/apk"
to = "/.netlify/functions/apks"
status = 200

[[redirects]]
from = "/apk/*"
to = "/.netlify/functions/apks/:splat"
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
